
[[csdprofile]]
[appendix,obligation="informative"]
== Profile: CalConnect standardization deliverables

=== General

This profile provides the specialization of the
_StandardDocument_ document metamodel for CalConnect standardization deliverables
described in <<CC10002>>.

The _CcStandardDocument_ model fully covers all CalConnect
standardization deliverables, including Standards,
Reports, Specifications, Directives, Guides, Amendments and Corrigenda.


=== Document and section specialization

The _CcStandardDocument_ model extends the _StandardDocument_
modelling of the document by requiring the following specific types
of section:

* An optional _Foreword_ (a `StandardsHierarchicalSection`, see <<standardssection>>).

* An optional _Introduction_ (a `StandardsHierarchicalSection`, see <<standardssection>>).

* One or more clause sections (see <<standardssection>>).

* Zero or more Annexes (see <<standardssection>>).


[[csdblock]]
=== Block specialization

The `Block` model is specialized:

* The definition of Figure is altered to allow ASCII artwork as an
option for its content, as a string (`pre`). As with the `sourcecode` element
(<<basicdocument>>), the string should be treated as pre-formatted
text, with whitespace treated as significant.


=== Inline elements specialization

The _CcStandardDocument_ model extends the _StandardDocument_
modelling of inline elements by one element:

* The `keyword` element is added as a subclass of Text Element
(<<basicdocument>>). The element is used to represent code keywords,
as with `code` in HTML, and should be rendered in monospace.


=== Document metadata specialization

==== General
////
The provisions which apply to ISO bibliographic entries (<<isobib>>)
also apply here.
////

The bibliographic modelling of CalConnect documents is further enriched compared
to _BibliographicItem_ as follows:

* The document type is constrained to be one of the following:
** _Standards_,
** _Reports_,
** _Specifications_,
** _Directives_,
** _Guides_,
** _Amendments_,
** _Corrigenda and Administrative_.

* The document status is constrained to be one of the following:
** _Proposal_,
** _Working Draft_,
** _Committee Draft_,
** _Final Draft_,
** _Published_,
** _Withdrawn_.

* The editorial group responsible for the document is defined with
a single components: a mandatory Technical Committee. The Technical
Committee has a type of either _Technical_ or _Provisional_.

lutaml_diagram::models/standoc-models/cc/models/CcMetadata.lml[]

==== CcBibliographicItem
[lutaml_uml_attributes_table,models/standoc-models/cc/models/CcMetadata.lml,CcBibliographicItem,skip]

==== CcTechnicalCommittee
[lutaml_uml_attributes_table,models/standoc-models/cc/models/CcMetadata.lml,CcTechnicalCommittee,skip]

==== CcDocumentStatus
[lutaml_uml_attributes_table,models/standoc-models/cc/models/CcMetadata.lml,CcDocumentStatus,skip]

==== CcStatusType
[lutaml_uml_attributes_table,models/standoc-models/cc/models/CcMetadata.lml,CcStatusType,skip]

==== CcDocumentType
[lutaml_uml_attributes_table,models/standoc-models/cc/models/CcMetadata.lml,CcDocumentType,skip]

==== CcTechnicalCommitteeType
[lutaml_uml_attributes_table,models/standoc-models/cc/models/CcMetadata.lml,CcTechnicalCommitteeType,skip]

